nohup: ignoring input
[I 2021-05-04 08:17:58.798 ServerApp] jupyterlab | extension was successfully linked.
[I 2021-05-04 08:17:58.798 ServerApp] jupyterlab_code_formatter | extension was successfully linked.
[I 2021-05-04 08:17:59.038 ServerApp] nbclassic | extension was successfully linked.
[I 2021-05-04 08:17:59.063 LabApp] JupyterLab extension loaded from /home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/jupyterlab
[I 2021-05-04 08:17:59.063 LabApp] JupyterLab application directory is /home/pan/anaconda3/envs/fast_env/share/jupyter/lab
[I 2021-05-04 08:17:59.068 ServerApp] jupyterlab | extension was successfully loaded.
[I 2021-05-04 08:17:59.069 ServerApp] jupyterlab_code_formatter | extension was successfully loaded.
[I 2021-05-04 08:17:59.073 ServerApp] nbclassic | extension was successfully loaded.
[I 2021-05-04 08:17:59.076 ServerApp] Serving notebooks from local directory: /home/pan/django_projects
[I 2021-05-04 08:17:59.076 ServerApp] Jupyter Server 1.4.1 is running at:
[I 2021-05-04 08:17:59.076 ServerApp] http://conda-20210309:4999/lab?token=cf4a93cc020e1221673a1a610f21bc610184bc9c4e63071a
[I 2021-05-04 08:17:59.076 ServerApp]  or http://127.0.0.1:4999/lab?token=cf4a93cc020e1221673a1a610f21bc610184bc9c4e63071a
[I 2021-05-04 08:17:59.076 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2021-05-04 08:17:59.079 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/pan/.local/share/jupyter/runtime/jpserver-15015-open.html
    Or copy and paste one of these URLs:
        http://conda-20210309:4999/lab?token=cf4a93cc020e1221673a1a610f21bc610184bc9c4e63071a
     or http://127.0.0.1:4999/lab?token=cf4a93cc020e1221673a1a610f21bc610184bc9c4e63071a
[I 2021-05-04 08:18:21.386 LabApp] Build is up to date
TermSocket.open: 1
[I 2021-05-04 08:18:21.812 ServerApp] New terminal with specified name: 1
TermSocket.open: Opened 1
Websocket closed
[I 2021-05-04 08:18:43.809 ServerApp] 302 POST /login?next=%2F (220.138.25.238) 1.56ms
[I 2021-05-04 08:18:43.841 ServerApp] 302 GET / (220.138.25.238) 0.67ms
[I 2021-05-04 08:18:47.021 LabApp] Build is up to date
TermSocket.open: 1
TermSocket.open: Opened 1
Websocket closed
[I 2021-05-04 08:19:29.898 LabApp] Build is up to date
[I 2021-05-04 08:19:46.729 LabApp] Build is up to date
TermSocket.open: 1
TermSocket.open: Opened 1
[I 2021-05-04 08:20:30.099 ServerApp] New terminal with automatic name: 2
TermSocket.open: 2
TermSocket.open: Opened 2
TermSocket.open: 1
TermSocket.open: Opened 1
Websocket closed
[I 2021-05-04 08:21:34.540 LabApp] Build is up to date
TermSocket.open: 1
TermSocket.open: Opened 1
TermSocket.open: 2
TermSocket.open: Opened 2
[W 2021-05-04 08:22:00.211 ServerApp] WebSocket ping timeout after 90002 ms.
Websocket closed
[W 2021-05-04 08:22:46.906 ServerApp] WebSocket ping timeout after 119964 ms.
Exception in callback BaseAsyncIOLoop._handle_events(18, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(18, 1)>
Traceback (most recent call last):
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/jupyter_server/terminal/handlers.py", line 32, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(18, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(18, 1)>
Traceback (most recent call last):
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/jupyter_server/terminal/handlers.py", line 32, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(18, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(18, 1)>
Traceback (most recent call last):
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/jupyter_server/terminal/handlers.py", line 32, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(18, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(18, 1)>
Traceback (most recent call last):
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/jupyter_server/terminal/handlers.py", line 32, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(18, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(18, 1)>
Traceback (most recent call last):
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/jupyter_server/terminal/handlers.py", line 32, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(18, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(18, 1)>
Traceback (most recent call last):
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/jupyter_server/terminal/handlers.py", line 32, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(18, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(18, 1)>
Traceback (most recent call last):
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/jupyter_server/terminal/handlers.py", line 32, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(18, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(18, 1)>
Traceback (most recent call last):
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/jupyter_server/terminal/handlers.py", line 32, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Websocket closed
TermSocket.open: 1
TermSocket.open: Opened 1
[I 2021-05-04 08:25:41.602 ServerApp] Kernel started: 2d13caa7-fb86-4420-9bb0-5cf28ed386b2
[I 2021-05-04 08:25:47.194 ServerApp] Kernel started: 1ca0eb49-90b6-4469-941a-93e8600a81ee
TermSocket.open: 1
TermSocket.open: Opened 1
[I 2021-05-04 09:12:51.012 ServerApp] Saving file at /fast_api_392/99.ipynb
[I 2021-05-04 09:36:30.180 ServerApp] Starting buffering for 1ca0eb49-90b6-4469-941a-93e8600a81ee:5f70a27d-8057-4f89-943b-86d6bc1a7a9c
Websocket closed
[I 2021-05-04 09:51:28.627 ServerApp] Starting buffering for 2d13caa7-fb86-4420-9bb0-5cf28ed386b2:e0c56670-9f7b-4cb7-af3b-484d6e9e807a
Websocket closed
Websocket closed
Websocket closed
[I 2021-05-04 09:56:38.532 LabApp] Build is up to date
TermSocket.open: 2
TermSocket.open: Opened 2
TermSocket.open: 1
TermSocket.open: Opened 1
Websocket closed
Websocket closed
[I 2021-05-04 10:59:19.700 LabApp] Build is up to date
TermSocket.open: 2
TermSocket.open: Opened 2
[W 2021-05-04 11:59:19.870 ServerApp] WebSocket ping timeout after 119964 ms.
Websocket closed
[I 2021-05-04 12:23:46.544 LabApp] Build is up to date
TermSocket.open: 2
TermSocket.open: Opened 2
Websocket closed
[I 2021-05-04 12:26:20.151 LabApp] Build is up to date
TermSocket.open: 2
TermSocket.open: Opened 2
[I 2021-05-04 12:26:41.061 ServerApp] Starting buffering for 2d13caa7-fb86-4420-9bb0-5cf28ed386b2:33487c6e-299c-4797-9fdf-4cb88a2822b1
Websocket closed
[I 2021-05-04 12:28:34.015 LabApp] Build is up to date
TermSocket.open: 2
TermSocket.open: Opened 2
[I 2021-05-04 12:30:36.228 ServerApp] Saving file at /fast_api_392/99.ipynb
[I 2021-05-04 12:32:32.920 ServerApp] Starting buffering for 2d13caa7-fb86-4420-9bb0-5cf28ed386b2:82992054-6b5b-4cd0-a0a4-94c6a37e66f3
Websocket closed
[I 2021-05-04 13:35:37.306 LabApp] Build is up to date
TermSocket.open: 2
TermSocket.open: Opened 2
[I 2021-05-04 13:47:13.336 ServerApp] Kernel restarted: 2d13caa7-fb86-4420-9bb0-5cf28ed386b2
[I 2021-05-04 13:47:13.363 ServerApp] Starting buffering for 2d13caa7-fb86-4420-9bb0-5cf28ed386b2:774a2370-c054-4258-8b3f-ef9ddebee4b3
[I 2021-05-04 13:47:13.409 ServerApp] Restoring connection for 2d13caa7-fb86-4420-9bb0-5cf28ed386b2:774a2370-c054-4258-8b3f-ef9ddebee4b3
[I 2021-05-04 13:47:15.952 ServerApp] Saving file at /fast_api_392/99.ipynb
[W 2021-05-04 14:52:07.522 ServerApp] WebSocket ping timeout after 119978 ms.
Websocket closed
[W 2021-05-04 14:52:13.410 ServerApp] WebSocket ping timeout after 119978 ms.
[I 2021-05-04 14:52:18.412 ServerApp] Starting buffering for 2d13caa7-fb86-4420-9bb0-5cf28ed386b2:774a2370-c054-4258-8b3f-ef9ddebee4b3
[I 2021-05-04 15:01:58.975 ServerApp] Restoring connection for 2d13caa7-fb86-4420-9bb0-5cf28ed386b2:774a2370-c054-4258-8b3f-ef9ddebee4b3
TermSocket.open: 2
TermSocket.open: Opened 2
[I 2021-05-04 15:56:51.065 ServerApp] Saving file at /fast_api_392/99.ipynb
[I 2021-05-04 15:58:51.168 ServerApp] Saving file at /fast_api_392/99.ipynb
[I 2021-05-04 15:59:04.135 ServerApp] Saving file at /fast_api_392/99.ipynb
[I 2021-05-04 15:59:10.043 ServerApp] Saving file at /fast_api_392/99.ipynb
[I 2021-05-04 15:59:17.337 ServerApp] Saving file at /fast_api_392/99.ipynb
[I 2021-05-04 15:59:25.452 ServerApp] Saving file at /fast_api_392/99.ipynb
[I 2021-05-04 15:59:32.085 ServerApp] Saving file at /fast_api_392/99.ipynb
[I 2021-05-04 15:59:35.644 ServerApp] Kernel restarted: 2d13caa7-fb86-4420-9bb0-5cf28ed386b2
[I 2021-05-04 15:59:35.662 ServerApp] Starting buffering for 2d13caa7-fb86-4420-9bb0-5cf28ed386b2:774a2370-c054-4258-8b3f-ef9ddebee4b3
[I 2021-05-04 15:59:35.694 ServerApp] Restoring connection for 2d13caa7-fb86-4420-9bb0-5cf28ed386b2:774a2370-c054-4258-8b3f-ef9ddebee4b3
[I 2021-05-04 16:01:26.307 ServerApp] Saving file at /fast_api_392/99.ipynb
[I 2021-05-04 16:05:29.784 LabApp] Build is up to date
[W 2021-05-04 16:41:02.964 ServerApp] WebSocket ping timeout after 119972 ms.
[W 2021-05-04 16:41:05.694 ServerApp] WebSocket ping timeout after 119974 ms.
Websocket closed
[I 2021-05-04 16:41:10.699 ServerApp] Starting buffering for 2d13caa7-fb86-4420-9bb0-5cf28ed386b2:774a2370-c054-4258-8b3f-ef9ddebee4b3
[I 2021-05-04 16:55:41.447 LabApp] Build is up to date
TermSocket.open: 2
TermSocket.open: Opened 2
Websocket closed
[I 2021-05-04 16:58:03.823 ServerApp] Starting buffering for 2d13caa7-fb86-4420-9bb0-5cf28ed386b2:dccd64ea-7362-4abe-b96c-0f07a1a098bf
[I 2021-05-04 17:09:21.504 LabApp] Build is up to date
TermSocket.open: 2
TermSocket.open: Opened 2
[I 2021-05-04 17:10:27.697 ServerApp] Starting buffering for 2d13caa7-fb86-4420-9bb0-5cf28ed386b2:292741f6-1f15-4c56-81f6-a0bdcb562bca
TermSocket.open: 1
TermSocket.open: Opened 1
