nohup: ignoring input
[I 2021-05-04 08:17:58.798 ServerApp] jupyterlab | extension was successfully linked.
[I 2021-05-04 08:17:58.798 ServerApp] jupyterlab_code_formatter | extension was successfully linked.
[I 2021-05-04 08:17:59.038 ServerApp] nbclassic | extension was successfully linked.
[I 2021-05-04 08:17:59.063 LabApp] JupyterLab extension loaded from /home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/jupyterlab
[I 2021-05-04 08:17:59.063 LabApp] JupyterLab application directory is /home/pan/anaconda3/envs/fast_env/share/jupyter/lab
[I 2021-05-04 08:17:59.068 ServerApp] jupyterlab | extension was successfully loaded.
[I 2021-05-04 08:17:59.069 ServerApp] jupyterlab_code_formatter | extension was successfully loaded.
[I 2021-05-04 08:17:59.073 ServerApp] nbclassic | extension was successfully loaded.
[I 2021-05-04 08:17:59.076 ServerApp] Serving notebooks from local directory: /home/pan/django_projects
[I 2021-05-04 08:17:59.076 ServerApp] Jupyter Server 1.4.1 is running at:
[I 2021-05-04 08:17:59.076 ServerApp] http://conda-20210309:4999/lab?token=cf4a93cc020e1221673a1a610f21bc610184bc9c4e63071a
[I 2021-05-04 08:17:59.076 ServerApp]  or http://127.0.0.1:4999/lab?token=cf4a93cc020e1221673a1a610f21bc610184bc9c4e63071a
[I 2021-05-04 08:17:59.076 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2021-05-04 08:17:59.079 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/pan/.local/share/jupyter/runtime/jpserver-15015-open.html
    Or copy and paste one of these URLs:
        http://conda-20210309:4999/lab?token=cf4a93cc020e1221673a1a610f21bc610184bc9c4e63071a
     or http://127.0.0.1:4999/lab?token=cf4a93cc020e1221673a1a610f21bc610184bc9c4e63071a
[I 2021-05-04 08:18:21.386 LabApp] Build is up to date
TermSocket.open: 1
[I 2021-05-04 08:18:21.812 ServerApp] New terminal with specified name: 1
TermSocket.open: Opened 1
Websocket closed
[I 2021-05-04 08:18:43.809 ServerApp] 302 POST /login?next=%2F (220.138.25.238) 1.56ms
[I 2021-05-04 08:18:43.841 ServerApp] 302 GET / (220.138.25.238) 0.67ms
[I 2021-05-04 08:18:47.021 LabApp] Build is up to date
TermSocket.open: 1
TermSocket.open: Opened 1
Websocket closed
[I 2021-05-04 08:19:29.898 LabApp] Build is up to date
[I 2021-05-04 08:19:46.729 LabApp] Build is up to date
TermSocket.open: 1
TermSocket.open: Opened 1
[I 2021-05-04 08:20:30.099 ServerApp] New terminal with automatic name: 2
TermSocket.open: 2
TermSocket.open: Opened 2
TermSocket.open: 1
TermSocket.open: Opened 1
Websocket closed
[I 2021-05-04 08:21:34.540 LabApp] Build is up to date
TermSocket.open: 1
TermSocket.open: Opened 1
TermSocket.open: 2
TermSocket.open: Opened 2
[W 2021-05-04 08:22:00.211 ServerApp] WebSocket ping timeout after 90002 ms.
Websocket closed
[W 2021-05-04 08:22:46.906 ServerApp] WebSocket ping timeout after 119964 ms.
Exception in callback BaseAsyncIOLoop._handle_events(18, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(18, 1)>
Traceback (most recent call last):
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/jupyter_server/terminal/handlers.py", line 32, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(18, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(18, 1)>
Traceback (most recent call last):
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/jupyter_server/terminal/handlers.py", line 32, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(18, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(18, 1)>
Traceback (most recent call last):
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/jupyter_server/terminal/handlers.py", line 32, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(18, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(18, 1)>
Traceback (most recent call last):
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/jupyter_server/terminal/handlers.py", line 32, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(18, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(18, 1)>
Traceback (most recent call last):
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/jupyter_server/terminal/handlers.py", line 32, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(18, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(18, 1)>
Traceback (most recent call last):
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/jupyter_server/terminal/handlers.py", line 32, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(18, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(18, 1)>
Traceback (most recent call last):
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/jupyter_server/terminal/handlers.py", line 32, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Exception in callback BaseAsyncIOLoop._handle_events(18, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(18, 1)>
Traceback (most recent call last):
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/management.py", line 212, in pty_read
    client.on_pty_read(s)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 73, in on_pty_read
    self.send_json_message(['stdout', text])
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/terminado/websocket.py", line 77, in send_json_message
    self.write_message(json_msg)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/jupyter_server/terminal/handlers.py", line 32, in write_message
    super(TermSocket, self).write_message(message, binary=binary)
  File "/home/pan/anaconda3/envs/fast_env/lib/python3.9/site-packages/tornado/websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
Websocket closed
TermSocket.open: 1
TermSocket.open: Opened 1
